name: calculadora
version: 0.1.0.0
github: "githubuser/calculadora"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/githubuser/calculadora#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- mtl
- selda
- selda-postgresql
- selda-sqlite

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  exposed-modules:
    - Lib
    - Util
    - MenuImposto
    - Contribuinte
    - Menu
    - Contrib
    - Paths_calculadora
  other-modules: []
  dependencies:
    - ansi-terminal
    - base >=4.7 && <5
    - mtl
    - selda
    - selda-postgresql
    - selda-sqlite
    - text
  language: Haskell2010

executables:
  calculadora-exe:
    main: Main.hs
    source-dirs:
      - app
      - src
    ghc-options:
      - Wall
      - Wcompat
      - Widentities
      - Wincomplete-record-updates
      - Wincomplete-uni-patterns
      - Wmissing-export-lists
      - Wmissing-home-modules
      - Wpartial-fields
      - Wredundant-constraints
      - threaded
      - rtsopts
      - with-rtsopts=-N
    dependencies:
      - calculadora
      - ansi-terminal
      - base >=4.7 && <5
      - mtl
      - selda
      - selda-postgresql
      - selda-sqlite
    language: Haskell2010

tests:
  calculadora-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - calculadora
      - ansi-terminal
      - base >=4.7 && <5
      - mtl
      - selda
      - selda-postgresql
      - selda-sqlite
      - text
      - selda-tests
